const seedIdeas = [
  {id:1,title:'Нова държавна платформа Casa 47 за по-достъпни наеми',summary:'Платформата стартира с над 800 жилища в Испания, включително 93 в Каталуния и 25 в провинция Barcelona.',tag:'Имоти',source:'Официален източник',age:'преди 2 часа',score:96,urgent:9,status:'inbox'},
  {id:2,title:'La Mercè 2026: пълната програма вече е публикувана',summary:'Концерти, castellers, светлинни спектакли и семейни събития от 23 до 27 септември на различни места в Barcelona.',tag:'Събития',source:'Barcelona.cat',age:'преди 4 часа',score:91,urgent:10,status:'inbox'},
  {id:3,title:'Промени в T-usual и обществения транспорт',summary:'Нови тарифи и условия за редовните пътуващи. Полезно практично съдържание за българите, които живеят или пристигат в града.',tag:'Барселона',source:'TMB',age:'днес',score:89,urgent:8,status:'inbox'},
  {id:4,title:'Безплатен вход в Sagrada Família за празника',summary:'Как местните жители могат да кандидатстват, важни срокове и какви документи са необходими.',tag:'Туризъм',source:'Sagrada Família',age:'днес',score:94,urgent:10,status:'newsletter'},
  {id:5,title:'Какво проверяваме преди капаро за имот в Каталуния',summary:'Образователен carousel с реалните стъпки: nota simple, тежести, comunidad, ITE и urbanistic status.',tag:'Имоти',source:'Лична идея',age:'вчера',score:87,urgent:4,status:'later'},
  {id:6,title:'Есенни занимания за деца в Barcelona',summary:'Селекция от достъпни културни, спортни и образователни занимания за семейства през октомври.',tag:'Семейство',source:'BCN Cultura',age:'вчера',score:82,urgent:5,status:'approved'}
];
let ideas = JSON.parse(localStorage.getItem('ccc-ideas') || 'null') || seedIdeas;
let currentView = 'inbox';
const views={inbox:['⌂','Inbox'],approved:['✓','Одобрени'],later:['◷','За по-късно'],newsletter:['✉','Бюлетин'],ready:['↗','За публикуване'],rejected:['×','Отхвърлени']};
const tags=['Барселона','Имоти','Туризъм','NIE и документи','Събития','Общност','Семейство'];
const save=()=>localStorage.setItem('ccc-ideas',JSON.stringify(ideas));
const toast=(msg)=>{const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
function renderNav(){document.querySelector('#nav').innerHTML=Object.entries(views).map(([key,[icon,label]])=>`<button class="nav-item ${key===currentView?'active':''}" data-view="${key}"><span>${icon}</span>${label}<span class="count">${ideas.filter(x=>x.status===key).length}</span></button>`).join('');document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()})}
function renderStats(){const data=[['✦',ideas.filter(x=>x.status==='inbox').length,'Нови идеи'],['✓',ideas.filter(x=>x.status==='approved').length,'Одобрени'],['✉',ideas.filter(x=>x.status==='newsletter').length,'За бюлетина'],['↗',ideas.filter(x=>x.status==='ready').length,'Готови постове']];document.querySelector('#stats').innerHTML=data.map(x=>`<div class="stat"><span class="stat-icon">${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div></div>`).join('')}
function renderTabs(){const tabs=[['inbox','Нови'],['approved','Одобрени'],['later','По-късно'],['newsletter','Бюлетин']];document.querySelector('#tabs').innerHTML=tabs.map(([v,l])=>`<button class="tab ${currentView===v?'active':''}" data-view="${v}">${l}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()})}
function tagClass(tag){return tag==='Имоти'?'property':tag==='Събития'?'event':''}
function card(i){return `<article class="idea-card"><div class="card-top"><span class="tag ${tagClass(i.tag)}">${i.tag}</span><span class="score">● ${i.score}% релевантност</span></div><h3>${i.title}</h3><p>${i.summary}</p><div class="card-meta"><span>◷ ${i.age}</span><a href="#">↗ ${i.source||'Лична идея'}</a><span>${i.urgent>=8?'⚡ Актуално сега':'◌ Evergreen'}</span></div><div class="card-actions"><button class="approve" data-action="approved" data-id="${i.id}">✓ Одобри</button><button data-action="later" data-id="${i.id}">◷ По-късно</button><button data-action="newsletter" data-id="${i.id}">✉ Бюлетин</button><button data-action="ready" data-id="${i.id}">↗ Създай пост</button><button class="more" data-action="rejected" data-id="${i.id}" title="Отхвърли">×</button></div></article>`}
function renderCards(){const q=document.querySelector('#search').value.toLowerCase(),tag=document.querySelector('#tagFilter').value,sort=document.querySelector('#sort').value;let list=ideas.filter(i=>i.status===currentView&&(!q||(i.title+' '+i.summary).toLowerCase().includes(q))&&(tag==='all'||i.tag===tag));list.sort((a,b)=>sort==='score'?b.score-a.score:sort==='urgent'?b.urgent-a.urgent:b.id-a.id);document.querySelector('#cards').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>Тук още няма идеи</h3><p>Премести идея в тази папка или добави нова.</p></div>`;document.querySelector('#resultCount').textContent=`${list.length} ${list.length===1?'идея':'идеи'}`;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>moveIdea(Number(b.dataset.id),b.dataset.action))}
function moveIdea(id,status){const idea=ideas.find(i=>i.id===id);idea.status=status;save();if(status==='ready')openExport(idea);toast(status==='rejected'?'Идеята е отхвърлена':`Запазено в „${views[status][1]}“`);render()}
function postText(i){return `${i.title}\n\n${i.summary}\n\nЗа кого е полезна тази информация и какво е важно да знаете? Подготвяме проверените детайли за вас. Запазете публикацията и я споделете с човек, на когото ще бъде полезна.\n\n#ZaBarcelona #Barcelona #БългариВИспания #ЖивотВБарселона #ПолезнаИнформация`}
function openExport(i){document.querySelector('#exportTitle').textContent=i.title;document.querySelector('#exportText').value=postText(i);document.querySelector('#exportDialog').showModal()}
function render(){renderNav();renderStats();renderTabs();document.querySelector('#viewTitle').textContent=views[currentView][1];document.querySelector('#viewSubtitle').textContent=currentView==='inbox'?'Прегледай и реши с един клик.':'Организирано съдържание според твоето решение.';renderCards()}
document.querySelector('#tagFilter').innerHTML+=tags.map(t=>`<option>${t}</option>`).join('');
['search','tagFilter','sort'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='search'?'input':'change',renderCards));
document.querySelector('#addBtn').onclick=()=>document.querySelector('#ideaDialog').showModal();
document.querySelector('#ideaForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const f=new FormData(e.currentTarget);ideas.push({id:Date.now(),title:f.get('title'),summary:f.get('summary'),tag:f.get('tag'),source:f.get('source')||'Лична идея',age:'току-що',score:85,urgent:5,status:'inbox'});save();e.currentTarget.reset();toast('Идеята е добавена');currentView='inbox';render()});
document.querySelector('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText(document.querySelector('#exportText').value);toast('Копирано — готово за Metricool')};
document.querySelector('#downloadBtn').onclick=()=>{const blob=new Blob([document.querySelector('#exportText').value],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='metricool-post.txt';a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#themeBtn').onclick=()=>toast('Тъмната тема ще дойде във версия 2');
render();
