const seedIdeas=[
{id:1,title:'Нова държавна платформа Casa 47 за по-достъпни наеми',summary:'Платформата стартира с над 800 жилища в Испания, включително 93 в Каталуния и 25 в провинция Barcelona.',tag:'Имоти',source:'Официален източник',age:'преди 2 часа',score:96,urgent:9,labels:['inbox']},
{id:2,title:'La Mercè 2026: пълната програма вече е публикувана',summary:'Концерти, castellers, светлинни спектакли и семейни събития от 23 до 27 септември на различни места в Barcelona.',tag:'Събития',source:'Barcelona.cat',age:'преди 4 часа',score:91,urgent:10,labels:['inbox']},
{id:3,title:'Промени в T-usual и обществения транспорт',summary:'Нови тарифи и условия за редовните пътуващи. Полезно практично съдържание за българите, които живеят или пристигат в града.',tag:'Барселона',source:'TMB',age:'днес',score:89,urgent:8,labels:['inbox']},
{id:4,title:'Безплатен вход в Sagrada Família за празника',summary:'Как местните жители могат да кандидатстват, важни срокове и какви документи са необходими.',tag:'Туризъм',source:'Sagrada Família',age:'днес',score:94,urgent:10,labels:['approved','newsletter']},
{id:5,title:'Какво проверяваме преди капаро за имот в Каталуния',summary:'Образователен carousel с реалните стъпки: nota simple, тежести, comunidad, ITE и urbanistic status.',tag:'Имоти',source:'Лична идея',age:'вчера',score:87,urgent:4,labels:['later','newsletter']},
{id:6,title:'Есенни занимания за деца в Barcelona',summary:'Селекция от достъпни културни, спортни и образователни занимания за семейства през октомври.',tag:'Семейство',source:'BCN Cultura',age:'вчера',score:82,urgent:5,labels:['approved']}];
let ideas=JSON.parse(localStorage.getItem('ccc-ideas')||'null')||seedIdeas;
ideas=ideas.map(i=>({...i,labels:i.labels||[i.status||'inbox']}));
let currentView='inbox';
const views={inbox:['⌂','Inbox'],approved:['✓','Одобрени'],later:['◷','За по-късно'],newsletter:['✉','Бюлетин'],ready:['↗','За публикуване'],rejected:['×','Отхвърлени']};
const tags=['Барселона','Имоти','Туризъм','NIE и документи','Събития','Общност','Семейство'];
const save=()=>localStorage.setItem('ccc-ideas',JSON.stringify(ideas));
const has=(idea,label)=>idea.labels.includes(label);
const toast=msg=>{const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
function renderNav(){document.querySelector('#nav').innerHTML=Object.entries(views).map(([key,[icon,label]])=>`<button class="nav-item ${key===currentView?'active':''}" data-view="${key}"><span>${icon}</span>${label}<span class="count">${ideas.filter(x=>has(x,key)).length}</span></button>`).join('');document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()})}
function renderStats(){const data=[['✦','inbox','Нови идеи'],['✓','approved','Одобрени'],['✉','newsletter','За бюлетина'],['↗','ready','Готови постове']];document.querySelector('#stats').innerHTML=data.map(([icon,key,label])=>`<div class="stat"><span class="stat-icon">${icon}</span><div><strong>${ideas.filter(x=>has(x,key)).length}</strong><small>${label}</small></div></div>`).join('')}
function renderTabs(){const tabs=[['inbox','Нови'],['approved','Одобрени'],['later','По-късно'],['newsletter','Бюлетин']];document.querySelector('#tabs').innerHTML=tabs.map(([v,l])=>`<button class="tab ${currentView===v?'active':''}" data-view="${v}">${l}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()})}
function tagClass(tag){return tag==='Имоти'?'property':tag==='Събития'?'event':''}
function card(i){const btn=(label,text,extra='')=>`<button class="${has(i,label)?'selected ':''}${extra}" data-action="${label}" data-id="${i.id}">${has(i,label)?'✓ ':''}${text}</button>`;return `<article class="idea-card"><div class="card-top"><span class="tag ${tagClass(i.tag)}">${i.tag}</span><span class="score">● ${i.score}% релевантност</span></div><h3>${i.title}</h3><p>${i.summary}</p><div class="active-labels">${i.labels.filter(x=>x!=='inbox').map(x=>`<span>${views[x]?.[1]||x}</span>`).join('')}</div><div class="card-meta"><span>◷ ${i.age}</span><a href="${i.url||'#'}" target="_blank">↗ ${i.source||'Лична идея'}</a><span>${i.urgent>=8?'⚡ Актуално сега':'◌ Evergreen'}</span></div><div class="card-actions">${btn('approved','Одобрено','approve')}${btn('later','По-късно')}${btn('newsletter','Бюлетин')}${btn('ready','Създай пост')}<button class="more ${has(i,'rejected')?'selected':''}" data-action="rejected" data-id="${i.id}" title="Отхвърли">×</button></div></article>`}
function renderCards(){const q=document.querySelector('#search').value.toLowerCase(),tag=document.querySelector('#tagFilter').value,sort=document.querySelector('#sort').value;let list=ideas.filter(i=>has(i,currentView)&&(!q||(i.title+' '+i.summary).toLowerCase().includes(q))&&(tag==='all'||i.tag===tag));list.sort((a,b)=>sort==='score'?b.score-a.score:sort==='urgent'?b.urgent-a.urgent:b.id-a.id);document.querySelector('#cards').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>Тук още няма идеи</h3><p>Избери този статус на идея или добави нова.</p></div>`;document.querySelector('#resultCount').textContent=`${list.length} ${list.length===1?'идея':'идеи'}`;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>toggleLabel(Number(b.dataset.id),b.dataset.action))}
function toggleLabel(id,label){const idea=ideas.find(i=>i.id===id),active=has(idea,label);if(label==='rejected'&&!active){idea.labels=['rejected']}else{idea.labels=idea.labels.filter(x=>x!=='rejected');idea.labels=active?idea.labels.filter(x=>x!==label):[...idea.labels,label];if(!idea.labels.length)idea.labels=['inbox'];if(label!=='inbox'&&!active)idea.labels=idea.labels.filter(x=>x!=='inbox')}save();if(label==='ready'&&!active)openExport(idea);toast(active?'Изборът е премахнат':`Добавено: ${views[label][1]}`);render()}
function postText(i){return `${i.title}\n\n${i.summary}\n\nЗа кого е полезна тази информация и какво е важно да знаете? Подготвяме проверените детайли за вас. Запазете публикацията и я споделете с човек, на когото ще бъде полезна.\n\n#ZaBarcelona #Barcelona #БългариВИспания #ЖивотВБарселона #ПолезнаИнформация`}
function openExport(i){document.querySelector('#exportTitle').textContent=i.title;document.querySelector('#exportText').value=postText(i);document.querySelector('#exportDialog').showModal()}
function render(){renderNav();renderStats();renderTabs();document.querySelector('#viewTitle').textContent=views[currentView][1];document.querySelector('#viewSubtitle').textContent=currentView==='inbox'?'Прегледай и избери един или няколко статуса.':'Една идея може да присъства в няколко папки.';renderCards()}
document.querySelector('#tagFilter').innerHTML+=tags.map(t=>`<option>${t}</option>`).join('');
['search','tagFilter','sort'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='search'?'input':'change',renderCards));
document.querySelector('#addBtn').onclick=()=>document.querySelector('#ideaDialog').showModal();
document.querySelector('#ideaForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const f=new FormData(e.currentTarget);ideas.push({id:Date.now(),title:f.get('title'),summary:f.get('summary'),tag:f.get('tag'),source:f.get('source')||'Лична идея',age:'току-що',score:85,urgent:5,labels:['inbox']});save();e.currentTarget.reset();toast('Идеята е добавена');currentView='inbox';render()});
document.querySelector('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText(document.querySelector('#exportText').value);toast('Копирано — готово за Metricool')};
document.querySelector('#downloadBtn').onclick=()=>{const blob=new Blob([document.querySelector('#exportText').value],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='metricool-post.txt';a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#themeBtn').onclick=()=>toast('Тъмната тема ще дойде във версия 2');
async function loadCollectedNews(){try{const res=await fetch('data/news.json',{cache:'no-store'});if(!res.ok)return;const incoming=await res.json(),known=new Set(ideas.flatMap(i=>[i.url,i.title]));incoming.forEach(n=>{if(!known.has(n.url)&&!known.has(n.title))ideas.push({...n,labels:['inbox']})});save();render()}catch(e){/* Offline mode uses saved ideas. */}}
render();loadCollectedNews();
