const {url:SUPABASE_URL,publishableKey:SUPABASE_KEY}=window.CCC_SUPABASE;
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,profile=null,brands=[],ideas=[],activeBrand=null,currentView='inbox',authMode='login',bootPromise=null;
const views={inbox:['⌂','Inbox'],approved:['✓','Одобрени'],later:['◷','За по-късно'],newsletter:['✉','Бюлетин'],ready:['↗','За публикуване'],rejected:['×','Отхвърлени']};
const tags=['Барселона','Имоти','Туризъм','NIE и документи','Събития','Общност','Семейство'];
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const has=(idea,label)=>(idea.labels||[]).includes(label);
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
const initials=name=>(name||'Б').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const ageOf=date=>{const hours=Math.max(0,Math.floor((Date.now()-new Date(date))/36e5));return hours<1?'току-що':hours<24?`преди ${hours} ч.`:hours<48?'вчера':`преди ${Math.floor(hours/24)} дни`};
$('#todayLabel').textContent=new Intl.DateTimeFormat('bg-BG',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase();

function setAuthMode(mode){authMode=mode;$$('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));$('#nameField').hidden=mode!=='register';$('#authTitle').textContent=mode==='login'?'Добре дошла отново':'Създай своя профил';$('#authSubtitle').textContent=mode==='login'?'Влез, за да продължиш към твоето съдържание.':'Започни безплатно с до три бранда.';$('.auth-submit').textContent=mode==='login'?'Вход':'Регистрация';$('#authMessage').textContent=''}
async function handleAuth(event){event.preventDefault();const form=new FormData(event.currentTarget),email=form.get('email').trim(),password=form.get('password');$('.auth-submit').disabled=true;$('#authMessage').textContent='';const result=authMode==='login'?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password,options:{data:{display_name:form.get('name')?.trim()||''},emailRedirectTo:location.href.split('#')[0]}});$('.auth-submit').disabled=false;if(result.error){$('#authMessage').textContent=bulgarianAuthError(result.error.message);return}if(authMode==='register'&&!result.data.session)$('#authMessage').textContent='Провери имейла си и потвърди регистрацията. След това се върни тук и влез.'}
function bulgarianAuthError(message){if(/invalid login/i.test(message))return'Грешен имейл или парола.';if(/already registered/i.test(message))return'Вече има регистрация с този имейл.';if(/password/i.test(message))return'Паролата трябва да бъде поне 8 символа.';return message}
async function ensureProfile(){const user=session.user;const {data,error}=await db.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;if(data){profile=data;return}const displayName=user.user_metadata?.display_name||user.email?.split('@')[0]||'';const created=await db.from('profiles').insert({id:user.id,display_name:displayName}).select().single();if(created.error)throw created.error;profile=created.data}
async function loadBrands(){const result=await db.from('brands').select('*').order('created_at');if(result.error)throw result.error;brands=result.data||[];const remembered=localStorage.getItem(`ccc-active-brand-${session.user.id}`);activeBrand=brands.find(b=>b.id===remembered)||brands.find(b=>b.is_active)||brands[0]||null;if(activeBrand)localStorage.setItem(`ccc-active-brand-${session.user.id}`,activeBrand.id)}
async function loadIdeas(){if(!activeBrand){ideas=[];render();return}const result=await db.from('content_ideas').select('*').eq('brand_id',activeBrand.id).order('created_at',{ascending:false});if(result.error)throw result.error;ideas=(result.data||[]).map(normalizeIdea);await migrateLocalIdeas();render()}
const normalizeIdea=i=>({...i,score:i.relevance,urgent:i.urgency,source:i.source_name,url:i.source_url,age:ageOf(i.created_at)});
async function migrateLocalIdeas(){const marker=`ccc-cloud-migrated-${session.user.id}`;if(localStorage.getItem(marker)||ideas.length)return;const local=JSON.parse(localStorage.getItem('ccc-ideas')||'null');if(!Array.isArray(local)||!local.length){localStorage.setItem(marker,'1');return}const rows=local.map(i=>({user_id:session.user.id,brand_id:activeBrand.id,title:i.title,summary:i.summary||'',tag:i.tag||'Барселона',source_name:i.source||'Лична идея',source_url:i.url||null,relevance:i.score||80,urgency:i.urgent||5,labels:i.labels||['inbox']}));const result=await db.from('content_ideas').insert(rows).select();if(!result.error){localStorage.setItem(marker,'1');ideas=result.data.map(normalizeIdea)}}
async function bootUser(){if(bootPromise)return bootPromise;bootPromise=(async()=>{$('#authScreen').classList.add('hidden');try{await ensureProfile();await loadBrands();updateIdentity();await loadIdeas();if(!brands.length&&!$('#brandEditorDialog').open)openBrandEditor()}catch(error){console.error(error);toast('Не успях да заредя профила. Опитай отново.')}})().finally(()=>{bootPromise=null});return bootPromise}
function updateIdentity(){const name=profile?.display_name||session?.user?.email?.split('@')[0]||'там';$('header h1').innerHTML=`Добър ден, ${esc(name)} <span>👋</span>`;$('#activeBrandName').textContent=activeBrand?.name||'Създай бранд';$('#brandMark').textContent=initials(activeBrand?.name);if(activeBrand?.logo_url)$('#brandMark').innerHTML=`<img src="${esc(activeBrand.logo_url)}" alt="">`}
function renderNav(){$('#nav').innerHTML=Object.entries(views).map(([key,[icon,label]])=>`<button class="nav-item ${key===currentView?'active':''}" data-view="${key}"><span>${icon}</span>${label}<span class="count">${ideas.filter(x=>has(x,key)).length}</span></button>`).join('');$$('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()})}
function renderStats(){const data=[['✦','inbox','Нови идеи'],['✓','approved','Одобрени'],['✉','newsletter','За бюлетина'],['↗','ready','Готови постове']];$('#stats').innerHTML=data.map(([icon,key,label])=>`<div class="stat"><span class="stat-icon">${icon}</span><div><strong>${ideas.filter(x=>has(x,key)).length}</strong><small>${label}</small></div></div>`).join('')}
function renderTabs(){const tabs=[['inbox','Нови'],['approved','Одобрени'],['later','По-късно'],['newsletter','Бюлетин']];$('#tabs').innerHTML=tabs.map(([v,l])=>`<button class="tab ${currentView===v?'active':''}" data-view="${v}">${l}</button>`).join('');$$('.tab').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()})}
function tagClass(tag){return tag==='Имоти'?'property':tag==='Събития'?'event':''}
function card(i){const btn=(label,text,extra='')=>`<button class="${has(i,label)?'selected ':''}${extra}" data-action="${label}" data-id="${i.id}">${has(i,label)?'✓ ':''}${text}</button>`,create=`<button class="${has(i,'ready')?'selected ':''}" data-create-post="${i.id}">${has(i,'ready')?'✓ ':''}Създай пост</button>`;const source=i.url?`<a href="${esc(i.url)}" target="_blank" rel="noopener">↗ ${esc(i.source||'Източник')}</a>`:`<span>↗ ${esc(i.source||'Лична идея')}</span>`;return `<article class="idea-card"><div class="card-top"><span class="tag ${tagClass(i.tag)}">${esc(i.tag)}</span><span class="score">● ${i.score}% релевантност</span></div><h3>${esc(i.title)}</h3><p>${esc(i.summary)}</p><div class="active-labels">${(i.labels||[]).filter(x=>x!=='inbox').map(x=>`<span>${esc(views[x]?.[1]||x)}</span>`).join('')}</div><div class="card-meta"><span>◷ ${esc(i.age)}</span>${source}<span>${i.urgent>=8?'⚡ Актуално сега':'◌ Evergreen'}</span></div><div class="card-actions">${btn('approved','Одобрено','approve')}${btn('later','По-късно')}${btn('newsletter','Бюлетин')}${create}<button class="more ${has(i,'rejected')?'selected':''}" data-action="rejected" data-id="${i.id}" title="Отхвърли">×</button></div></article>`}
function renderCards(){const q=$('#search').value.toLowerCase(),tag=$('#tagFilter').value,sort=$('#sort').value;let list=ideas.filter(i=>has(i,currentView)&&(!q||(i.title+' '+i.summary).toLowerCase().includes(q))&&(tag==='all'||i.tag===tag));list.sort((a,b)=>sort==='score'?b.score-a.score:sort==='urgent'?b.urgent-a.urgent:new Date(b.created_at)-new Date(a.created_at));$('#cards').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>Тук още няма съдържание</h3><p>${activeBrand?'Новините ще се появят след автоматичното събиране. Ръчното добавяне е само по желание.':'Създай първия си бранд, за да започнеш.'}</p><button class="primary" id="emptyAction">${activeBrand?'↻ Провери отново':'＋ Създай бранд'}</button></div>`;$('#resultCount').textContent=`${list.length} ${list.length===1?'идея':'идеи'}`;$$('[data-action]').forEach(b=>b.onclick=()=>toggleLabel(b.dataset.id,b.dataset.action));$$('[data-create-post]').forEach(b=>b.onclick=()=>openPostRequest(ideas.find(i=>i.id===b.dataset.createPost)));if($('#emptyAction'))$('#emptyAction').onclick=()=>activeBrand?loadIdeas():openBrandEditor()}
function renderOnboarding(){const approved=ideas.filter(i=>has(i,'approved')&&!has(i,'rejected')),firstPostQueued=localStorage.getItem(`ccc-first-post-${session.user.id}`)==='1',complete=activeBrand&&approved.length&&firstPostQueued;$('#onboarding').hidden=Boolean(complete);if(complete)return;const steps=[{done:Boolean(activeBrand),title:'1. Създай бранд',text:activeBrand?activeBrand.name:'Добави име, описание, език и лого.',action:'brand',button:activeBrand?'Прегледай':'Създай бранд'},{done:approved.length>0,title:'2. Одобри съдържание',text:approved.length?`${approved.length} ${approved.length===1?'пост е одобрен':'поста са одобрени'}.`:'Прегледай автоматично събраните предложения в Inbox.',action:'inbox',button:'Към Inbox'},{done:firstPostQueued,title:'3. Създай пост',text:firstPostQueued?'Първата заявка е изпратена.':'Избери одобрен пост, канали, дата и час.',action:'post',button:'Създай пост'}];$('#onboardingSteps').innerHTML=steps.map(s=>`<article class="onboarding-step ${s.done?'done':''}"><span class="step-check">${s.done?'✓':'○'}</span><div><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><button class="${s.done?'ghost':'primary'}" data-onboarding="${s.action}">${esc(s.button)}</button></div></article>`).join('');$$('[data-onboarding]').forEach(b=>b.onclick=()=>{if(b.dataset.onboarding==='brand')activeBrand?openBrands():openBrandEditor();if(b.dataset.onboarding==='inbox'){currentView='inbox';render()}if(b.dataset.onboarding==='post')openPostRequest()})}
function render(){renderNav();renderStats();renderTabs();renderOnboarding();$('#viewTitle').textContent=views[currentView][1];$('#viewSubtitle').textContent=currentView==='inbox'?'Прегледай и избери един или няколко статуса.':'Една идея може да присъства в няколко папки.';renderCards();updateIdentity()}
async function toggleLabel(id,label){const idea=ideas.find(i=>i.id===id),active=has(idea,label);if(!idea)return;let labels;if(label==='rejected'&&!active)labels=['rejected'];else{labels=idea.labels.filter(x=>x!=='rejected');labels=active?labels.filter(x=>x!==label):[...labels,label];if(!labels.length)labels=['inbox'];if(label!=='inbox'&&!active)labels=labels.filter(x=>x!=='inbox')}const result=await db.from('content_ideas').update({labels,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(result.error){toast('Промяната не беше запазена.');return}idea.labels=labels;if(label==='ready'&&!active)openPostRequest(idea);toast(active?'Изборът е премахнат':`Добавено: ${views[label][1]}`);render()}
function postText(i){const brand=activeBrand?.name||'Нашият бранд';return `${i.title}\n\n${i.summary}\n\nЗа кого е полезна тази информация и какво е важно да знаете? Подготвяме проверените детайли за вас. Запазете публикацията и я споделете с човек, на когото ще бъде полезна.\n\n#${brand.replace(/\s+/g,'')} #Barcelona #ПолезнаИнформация`}
function openExport(i){$('#exportTitle').textContent=i.title;$('#exportText').value=postText(i);$('#exportDialog').showModal()}
function nextPublishTime(){const d=new Date();d.setDate(d.getDate()+1);d.setHours(10,0,0,0);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function openIdeaDialog(){if(!activeBrand){openBrandEditor();return}$('#ideaDialog').showModal()}
function openPostRequest(i=null){if(!activeBrand){toast('Първо създай бранд.');openBrandEditor();return}const approved=ideas.filter(idea=>has(idea,'approved')&&!has(idea,'rejected')),available=approved.length?approved:ideas.filter(idea=>!has(idea,'rejected'));if(!i&&!available.length){toast('Няма съдържание за пост. Изчакай автоматичното събиране.');return}const selected=i||available[0],form=$('#postRequestForm');form.reset();$('#selectedPostIdeaId').value=selected.id;$('#postIdeaPicker').hidden=Boolean(i);$('#postIdeaSelect').innerHTML=i?'':available.map(idea=>`<option value="${idea.id}" ${idea.id===selected.id?'selected':''}>${esc(idea.title)}</option>`).join('');form.target_brand.value=selected.tag==='Имоти'?'imoti':'za_barcelona';form.requested_for.value=nextPublishTime();$$('#postRequestForm input[name="channels"]').forEach(x=>x.checked=true);$('#requestTitle').textContent=selected.title;$('#postRequestDialog').showModal()}
async function queuePostRequest(event){event.preventDefault();const f=new FormData(event.currentTarget),channels=f.getAll('channels');if(!channels.length){toast('Избери поне един канал.');return}const idea=ideas.find(i=>i.id===f.get('idea_id'));if(!idea){toast('Избери идея за публикацията.');return}const target=f.get('target_brand'),metricoolId=target==='imoti'?5598358:5598360,requested=new Date(f.get('requested_for'));if(Number.isNaN(requested.getTime())){toast('Избери валидна дата и час.');return}const row={user_id:session.user.id,brand_id:activeBrand.id,idea_id:idea.id,target_brand:target,metricool_brand_id:metricoolId,channels,requested_for:requested.toISOString(),status:'queued'};const result=await db.from('post_requests').insert(row).select().single();if(result.error){console.error(result.error);toast('Заявката не беше записана.');return}if(!has(idea,'ready')){const labels=[...idea.labels.filter(x=>x!=='inbox'&&x!=='rejected'),'ready'];const updated=await db.from('content_ideas').update({labels,updated_at:new Date().toISOString()}).eq('id',idea.id).select().single();if(!updated.error)idea.labels=labels}localStorage.setItem(`ccc-first-post-${session.user.id}`,'1');$('#postRequestDialog').close();render();toast('Заявката е добавена за обработка до 1 час.')}
async function addIdea(event){event.preventDefault();if(!activeBrand){toast('Първо създай бранд.');return}const f=new FormData(event.currentTarget),source=f.get('source')?.trim(),row={user_id:session.user.id,brand_id:activeBrand.id,title:f.get('title'),summary:f.get('summary'),tag:f.get('tag'),source_name:source||'Лична идея',source_url:/^https?:\/\//i.test(source)?source:null,relevance:85,urgency:5,labels:['inbox']};const result=await db.from('content_ideas').insert(row).select().single();if(result.error){toast('Идеята не беше запазена.');return}ideas.unshift(normalizeIdea(result.data));event.currentTarget.reset();$('#ideaDialog').close();toast('Идеята е добавена');currentView='inbox';render()}
function openProfile(){const form=$('#profileForm');form.display_name.value=profile?.display_name||'';form.business_description.value=profile?.business_description||'';form.default_language.value=profile?.default_language||'bg';form.ai_preferences.value=profile?.ai_preferences||'';form.email.value=session.user.email||'';$('#profileDialog').showModal()}
async function saveProfile(event){event.preventDefault();const f=new FormData(event.currentTarget),changes={display_name:f.get('display_name').trim(),business_description:f.get('business_description').trim(),default_language:f.get('default_language'),ai_preferences:f.get('ai_preferences').trim(),updated_at:new Date().toISOString()};const result=await db.from('profiles').update(changes).eq('id',session.user.id).select().single();if(result.error){toast('Профилът не беше запазен.');return}profile=result.data;$('#profileDialog').close();updateIdentity();toast('Профилът е запазен')}
function renderBrandList(){$('#brandList').innerHTML=brands.length?brands.map(b=>`<div class="brand-row ${activeBrand?.id===b.id?'active':''}"><button class="brand-select" data-brand-select="${b.id}">${b.logo_url?`<img src="${esc(b.logo_url)}" alt="">`:`<span>${initials(b.name)}</span>`}<div><b>${esc(b.name)}</b><small>${esc(b.language.toUpperCase())} · ${esc(b.tone)}</small></div></button><button class="icon-btn" data-brand-edit="${b.id}" title="Редактирай">✎</button></div>`).join(''):'<p class="empty-small">Все още нямаш бранд.</p>';$('#newBrandBtn').disabled=brands.length>=3;$('#brandLimitNote').textContent=brands.length>=3?'Достигнат е лимитът от 3 бранда.':'До 3 бранда в безплатната версия.';$$('[data-brand-select]').forEach(b=>b.onclick=async()=>{activeBrand=brands.find(x=>x.id===b.dataset.brandSelect);localStorage.setItem(`ccc-active-brand-${session.user.id}`,activeBrand.id);$('#brandsDialog').close();await loadIdeas()});$$('[data-brand-edit]').forEach(b=>b.onclick=()=>openBrandEditor(brands.find(x=>x.id===b.dataset.brandEdit)))}
function openBrands(){renderBrandList();$('#brandsDialog').showModal()}
function openBrandEditor(brand=null){if(!brand&&brands.length>=3){toast('Можеш да имаш максимум 3 бранда.');return}const form=$('#brandForm');form.reset();form.brand_id.value=brand?.id||'';form.name.value=brand?.name||'';form.description.value=brand?.description||'';form.language.value=brand?.language||'bg';form.tone.value=brand?.tone||'приятелски, конкретен и полезен';$('#brandEditorTitle').textContent=brand?'Редактирай бранд':'Създай бранд';if($('#brandsDialog').open)$('#brandsDialog').close();$('#brandEditorDialog').showModal()}
async function uploadLogo(file){if(!file?.size)return null;if(file.size>2097152)throw new Error('Логото трябва да е до 2 MB.');const ext=(file.name.split('.').pop()||'png').toLowerCase(),path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const upload=await db.storage.from('brand-logos').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;return db.storage.from('brand-logos').getPublicUrl(path).data.publicUrl}
async function saveBrand(event){event.preventDefault();const f=new FormData(event.currentTarget),id=f.get('brand_id');try{const logo=await uploadLogo(f.get('logo'));const values={name:f.get('name').trim(),description:f.get('description').trim(),language:f.get('language'),tone:f.get('tone').trim()||'приятелски, конкретен и полезен',updated_at:new Date().toISOString()};if(logo)values.logo_url=logo;const result=id?await db.from('brands').update(values).eq('id',id).select().single():await db.from('brands').insert({...values,user_id:session.user.id,is_active:!brands.length}).select().single();if(result.error)throw result.error;await loadBrands();activeBrand=brands.find(b=>b.id===result.data.id)||activeBrand;localStorage.setItem(`ccc-active-brand-${session.user.id}`,activeBrand.id);$('#brandEditorDialog').close();await loadIdeas();toast(id?'Брандът е обновен':'Брандът е създаден')}catch(error){console.error(error);toast(error.message.includes('3 бранда')?error.message:'Брандът не беше запазен.')}}
$$('[data-auth-mode]').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.authMode));
$('#authForm').addEventListener('submit',handleAuth);$('#ideaForm').addEventListener('submit',addIdea);$('#profileForm').addEventListener('submit',saveProfile);$('#brandForm').addEventListener('submit',saveBrand);$('#postRequestForm').addEventListener('submit',queuePostRequest);
$('#profileBtn').onclick=openProfile;$('#switchBrandBtn').onclick=openBrands;$('#newBrandBtn').onclick=()=>openBrandEditor();$('#logoutBtn').onclick=async()=>{await db.auth.signOut();$('#profileDialog').close()};$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#addBtn').onclick=openIdeaDialog;$('#createPostBtn').onclick=()=>openPostRequest();$('#postIdeaSelect').onchange=event=>{const idea=ideas.find(i=>i.id===event.target.value);if(idea){$('#selectedPostIdeaId').value=idea.id;$('#requestTitle').textContent=idea.title;$('#postRequestForm').target_brand.value=idea.tag==='Имоти'?'imoti':'za_barcelona'}};$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('#exportText').value);toast('Копирано — готово за Metricool')};$('#downloadBtn').onclick=()=>{const blob=new Blob([$('#exportText').value],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='metricool-post.txt';a.click();URL.revokeObjectURL(a.href)};
$('#tagFilter').innerHTML+=tags.map(t=>`<option>${t}</option>`).join('');['search','tagFilter','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderCards));
db.auth.onAuthStateChange((_event,nextSession)=>{session=nextSession;if(session)bootUser();else{$('#authScreen').classList.remove('hidden');profile=null;ideas=[];brands=[];activeBrand=null}});
db.auth.getSession().then(({data})=>{session=data.session;if(session)bootUser();else $('#authScreen').classList.remove('hidden')});
